<?php

namespace Customize\Repository;

use Eccube\Common\EccubeConfig;
use Eccube\Doctrine\Query\Queries;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;
use Eccube\Repository\ProductRepository as BaseProductRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends BaseProductRepository
{
    public function __construct(RegistryInterface $registry, Queries $queries, EccubeConfig $eccubeConfig) {
        parent::__construct($registry, $queries, $eccubeConfig);
    }

    public function findByCustomCode($code)
    {
        $queryBuilder = $this->createQueryBuilder('p')
            ->where('p.custom_code = :code')
            ->setParameter('code', $code);

        return $queryBuilder->getQuery()->getResult();
    }
}
